Repository backend-tech-study/posting-study, pull requests merged in 2022-02, with the labels that each got.

#16 [주오] 3주차 포스팅
  week#1/LeeJuOh.md
  week#2/LeeJuOh.md
  week#2/heoseungyeon.md
  week#3/LeeJuOh.md
Labels: posting, spring

#17 [주오] 4주차 포스팅
  week#4/LeeJuOh.md
Labels: posting, java

#21 [승연] 5th 포스팅
  week#5/heoseungyeon.md
Labels: posting
