Repository backend-tech-study/posting-study, pull requests merged in 2022-01, with the labels that each got.

#3 [주오] 1주차 포스팅
  .idea/.gitignore
  week#1/LeeJuOh.md
Labels: java, spring

#8 [주오] 1주차 포스팅
  .gitignore
  week#1/LeeJuOh.md
Labels: posting, java

#12 [승연] 2주차 포스팅
  week#2/heoseungyeon.md
Labels: posting, spring

#11 [주오] 2주차 포스팅
  week#2/LeeJuOh.md
Labels: posting, spring
